name: Release Retina Charts

on:
  push:
    branches: ["test-sign-released-images"]
    tags: ["v*"]

permissions:
  contents: read
  packages: write
  # This is used to complete the identity challenge
  # with sigstore/fulcio when running outside of PRs.
  id-token: write

jobs:
  push-retina-charts:
    name: Publish Retina Helm Charts
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: azure/setup-helm@v4.1.0
        id: install
      
      - name: Install Cosign
        uses: sigstore/cosign-installer@v3.4.0

      - name: Log in to registry
        run: echo "${{ secrets.GITHUB_TOKEN }}" | helm registry login ghcr.io -u $ --password-stdin
      
      - name: Build, Push and Sign Chart
        id: build_chart
        shell: bash
        run: |
          set -euo pipefail
          export TAG=$(make version)
          echo "TAG=$TAG" >> $GITHUB_OUTPUT
          echo $TAG
          helm package ./deploy/manifests/controller/helm/retina --version $TAG
          helm push retina-$TAG.tgz oci://ghcr.io/${{ github.repository }}/charts >> helm_push_result.txt 2>&1
          cosign sign --yes ghcr.io/${{ github.repository }}/charts/retina@$(tail -n 1 helm_push_result.txt | awk '{ print $2 }')
      